<?php

    namespace App\Models;

//    use Connect\Database\Postgres;


    class Model {

        private $conn;

        public function __construct()
        {
            echo "Delekkek";
        }

        public function query()
        {
            // TODO: Change the autogenerated stub
        }
    }